
# =========================================================================
# --- Check that sequence is valid --------------------------------------------
# =========================================================================


sequence_check <- function(sequence){
  sequence <- str_to_upper(sequence)
  ((nchar(sequence) >= 300) &  
   (str_detect(sequence, "[^ACGTRYSWKMBDHVN]", negate = TRUE)))   
}

# =========================================================================
# --- Match all ASVs (pattern) to query sequences -----------------------------
# =========================================================================

# Compute % of ID for each ASV versus query sequence and order by decreasing PID

match_asv <- function(fasta.df, query){
  
  query <-  Biostrings::DNAString(query)
  
  pattern <- Biostrings::DNAStringSet(fasta.df$sequence)
  names(pattern) <- fasta.df$asv_code
  
  asv_align <- Biostrings::pairwiseAlignment(pattern = pattern, subject = query, type = "global-local")
  
  scores <- data.frame(score=Biostrings::score(asv_align), pid = Biostrings::pid(asv_align) )
  
  bind_cols(fasta.df, scores) %>%
    arrange(desc(pid)) %>% 
    mutate(pid = round(pid, 2)) %>%  # Only 2 decimals
    select(asv_code, pid, kingdom:species, sequence,
           asv_remark, sum_reads_asv)
}


# =========================================================================
# --- Test sequences ----------------------------------------------------------
# =========================================================================

# Long - Micromonas - GenBank
query_01 = "ACCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCGTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGCAATAGTTTCTTTGGTGGTGTTTACTACATGGATAACCGTAGTAATTCTAGAGCTAATACATGCGTAAATCCCGACTTCGGAAGGGACGTATTTATTAGATAAAGACCGACCTCGTTCTGCGGTGAATCATGATAACTTCACGGACCGCATGGCCTCGCGCCGGCGGTGTTCCATTCAAATTTCTGCCCTATCAACTTTCGACGGTAGGATAGAGGCCTACCGTGGTGTTCACGGGTGACGGAGAATTAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCTGACACAGGGAGGTAGTGACAATAAATAACAATATCGGGGTTTTTCAACTCTGATAATTGGAATGAGAACAATCTAAATCCCTTAACGAGGATCCATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTTAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCGGTTAAGAGCGACCGGTCCGCCGTTTGGTGTGCACTGGTTGGTTTTAACTTCCTGTAGAGGACGTGCTCTGGGTTTAACGACCTGGACTCGGAGTCTACGTGGTTACTTTGAAAAAATTAGAGTGTTCAAAGCGGGCTTACGCTTGAATATTTCAGCATGGAATAACACTATAGGACTCCTGTCCTATTTCGTTGGTCTCGGGACGGGAGTAATGATTAAGAGGAACAGTTGGGGGCATTCGTATTTCATTGTCAGAGGTGAAATTCTTGGATTTATGAAAGACGAACTTCTGCGAAAGCATTTGCCAAGGATGTTTTCATTAATCAAGAACGAAAGTTGGGGGCTCGAAGATGATTAGATACCATCCTAGTCTCAACCATAAACGATGCCGACTAGGGATTGGCGGATGTTAATTGATGACTCCGCCAGCACCTTATGAGAAATCAAAGTTTTTGGGTTCCGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACCAGGCGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTTACCAGGTCCAGACATAGTAAGGATTGACAGATTGAGAGCTCTTTCTTGATTCTATGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGTTAACGAACGAGACCTCAGCCTGCTAAATAGTTGTACGCTACTCTTAGCGCAGCAACTTCTTAGAGGGACTATTGGCGTTTAGCCAATGGAAGTTTGAGGCAATAACAGGTCTGTGATGCCCTTAGATGTTCTGGGCCGCACGCGCGCTACACTGACGAATGCAACGAGCTTATAACCTTGGCCGAAAGGTCTGGGTAATCTCCAAATTTCGTCGTGATGGGGATAGATTATTGCAATTATTAATCTTCAACGAGGAATGCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTCCTACCGATTGAATGGTCCGGTGAAGCGCTCGGACCGCGGCCTCTTGACGGTTCGCTGTCGATTGGCTGTGGGAAGTTCGTTAAACCTTATCATTTAGAGGAAGGAGAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCAGAAGGATCA"

# Short Dino - Barcode
query_02 = "GTAGTTGGATTTCTGTTGAGGACGGCCGGTCCGCACTATGTGCGTGTATCTGGTTCGGCCTCGGCATCCTCTTGAGGAACGTTTCTGCGCTTGATTGCGTGGAGCGGTATTCAAGACTTTTACTTTGAGGAAATTAGAGTGTTCACGGCAGGCAAGCGCCTTGAATACATTAGCATGGAATAATAATATAGGATCTTGGTTCTATTTGTTGGTTTCTAGGGCTAAGGTAATGATTAATAGGGATAATTGGGGGCATTTGTATTAACGCGT"

query_03 = str_sub(query_01,1,100)
